#!/usr/bin/bash

# Help menu
if [ ${#@} -eq 0 ]; then
    echo -e '\033[0;34mCompile GGINE game\033[0m'
    echo -e 'syntax: \033[1;30m./run {game name}\033[0m'
    echo -e '\033[0;34mspecial actions:\033[0m'
    echo -e '  - \033[1;30m./run merge\033[0m - Merges the work of chenlin and jason into noblecity'
    exit
fi
n="$1"

# Merge command
if [ "$n" == 'merge' ]; then
    tsj="game/noblecity_jazo.ts"
    tsc="game/noblecity_chen.ts"
    tsm="game/noblecity.ts"
    if [ -f "$tsj" ] && [ -f "$tsc" ]; then
        diff --line-format %L "$tsj" "$tsc" > "$tsm"
    else
        cp -p "$tsm" "$tsj"
        cp -p "$tsm" "$tsc"
    fi
    exit
fi

# Esbuild typescript
esbuild game/$n.ts --bundle --outfile=$n.js --platform=browser --minify --watch=forever &
watch=$!
echo "Watching esbuild at $watch"

# Compiling to html
while true; do
    if [ -f "$n.js" ]; then
        {
            echo -n '<!DOCTYPE html><html><head><title>Noble City</title><style>html,body{background-color:#111;width:100%;height:100%;margin:0;padding:0;overflow:hidden;display:flex;justify-content:center;align-items:center;}canvas{display:block;image-rendering:pixelated;object-fit:contain;box-shadow:0 0 30px #000}</style></head><body><canvas id="game"></canvas><script>'
            printf "%s" "$(cat $n.js)"
            echo -n '</script></body></html>'
        } > "$n.html"
        rm $n.js
        echo "Compiled into $n.html"
    fi
    sleep 1
done
trap 'kill $watch' EXIT